### ISSUE TITLE
Run several mesos-consul in parallel

### ISSUE THREAD

**Issue by chaen** [mantl/mesos-consul#110]
Hi,

I couldn't find in the documentation whether it is ok to run several mesos-consul in parallel ? is there no risk of duplicated services/splitbrain or whatever ? 

Thanks
Chris

**Comment by stevendborrelli** [comment]
You probably should only run one process, as it connects to the consul daemons on each system to register them.  There's really not a big risk of split brain in the process itself, it queries mesos and then registers the tasks on each consul node.

**Comment by chaen** [comment]
Yeah, but then this becomes a single point of failure :-/ Any way around that ?

**Comment by stevendborrelli** [comment]
We usually have run it via Marathon, so that it gets restarted if it dies. If you want stronger HA, maybe look at implementing a lock among multiple mesos-consul process via consul locks.

**Comment by chaen** [comment]
Well that is exactly what I do as well :-)
I was just worried of the bootstrapping problem in case of failure, since I generate mesos' whitelist from that.
Thanks !

**Comment by mnp** [comment]
We came to the same conclusion here.  Run one, and let Marathon deal with restarting it.  If it dies, you might wait a few seconds before a replacement starts up, which is okay because the poll cycle is a minute anyway.  We thought about multiple instances and decided against it.
